### ISSUE TITLE
dist depends on external `debounce` function

### ISSUE THREAD

**Issue by sundarj** [skatejs/named-slots#113]
The 1.0.1 release on npm throws a TypeError `Cannot use 'in' operator to search for 'default' in undefined` because it depends on `debounce` being present in the environment instead of bundling it. 
See https://jsfiddle.net/j22vhcdu/

the wzrd.in version works however, because it bundles debounce.

**Comment by treshugart** [comment]
Hey @sundarj, sorry for the delayed response. I seem to have unwatched the repo (not on purpose). Would this be resolved for you in any of the later releases?

**Comment by sundarj** [comment]
Yep, it works now!

Thanks a bunch.
