### ISSUE TITLE
Does not install with jspm because dependency doesn't exist

### ISSUE THREAD

**Issue by robhicks** [skatejs/named-slots#115]
When attempting to install name-slots with jspm the following error is reported:

```
jspm install npm:skatejs-named-slots
Updating registry cache...
ok   Installed npm:debounce@^1.0.0 (1.0.0)
ok   Installed npm:date-now@1.0.1 (1.0.1)

err  Installing npm:skatejs-named-slots@1.1.0, no version match for github:joscha/custom-event-polyfill@de24bd9
```

I have verified that commit de24bd9 does exist in joscha/custom-event-polyfill repo. When npm installs it ignores the commit hash and installs custom-event-polyfill@0.2.2.

Can this be fixed so jspm can be used?

**Comment by treshugart** [comment]
Hey @robhicks, sorry for the delayed response. For some reason I wasn't watching the repo so I didn't get notifications. Odd.

Is this fixed in the latest version?

**Comment by robhicks** [comment]
No it is not fixed in the latest version. 
I checked on the jspm gitter channel and found out that jspm does not support installing dependencies with github commit hashes. Dependencies need to reference tagged releases or name branches.

**Comment by treshugart** [comment]
I'll have a look. I'm not sure we even need the dep in question anymore.
