### ISSUE TITLE
Safari doesn't properly update childNodes of a parent node after a node has been appended to a different node

### ISSUE THREAD

**Issue by ryansolid** [skatejs/named-slots#118]
Basically copy this in your console and you will see the difference between browsers:

parent1 = document.createElement('div');
parent2 = document.createElement('div');
parent1.appendChild(document.createElement('span'));
parent2.appendChild(parent1.firstChild);
parent1.childNodes;

You will see parent 1 still has the span in Safari where the other browsers show an empy nodeList.
This was testing on Safari 9.1.2

**Comment by treshugart** [comment]
Sorry for the delayed response, @ryansolid. I don't think I got a notification. 

I think @nadiam84 may have had a similar issue recently?

**Comment by adevnadia** [comment]
I don't think so but I'll take a look
