### ISSUE TITLE
Polyfill Text interface for relevant DOM methods / properties.

### ISSUE THREAD

**Issue by treshugart** [skatejs/named-slots#50]
Currently the `Text`interface isn't polyfilled, only `HTMLElement` is. Due to WebKit, we can't polyfill everything at the `Node` level so we must selectively patch the interfaces at the highest point in the prototype chain. This means `Text` needs to be polyfilled with the methods and properties that it shares with `HTMLElement`

To reproduce the issue, create an element with a shadow root that has an text node between two element nodes in the light DOM, but where the text node gets projected to a different spot than the element nodes. When using `previousSibling` and `nextSibling`, it should currently return `null`. Once polyfilled, it should return the element nodes.

https://developer.mozilla.org/en/docs/Web/API/Text

**Comment by treshugart** [comment]
@lukebatchelor is this fixed now?

**Comment by lukebatchelor** [comment]
I thought it was... I must not have linked it to my PR?
